---
  - name: Users Management 
    hosts: "{{ group }}"
    gather_facts: "{{ gather_facts }}"
    vars_files: 
      - "../variables/addusers-values.yaml" 
    tasks: 
    # Task for User 1 - values defined in ../variables/addusers-values.yaml
      - name: User 1
        user: 
          name: "{{ name_user1 }}"
          uid: "{{ uid_1 }}"
    # Task for User 1 - values defined in ../variables/addusers-values.yaml
      - name: User 1
        user: 
          name: "{{ name_user2 }}"
          uid: "{{ uid_2 }}"