---
  - name: Ping Hosts Managed Hosts
    hosts: "{{ group }}"
    gather_facts: no
    vars_files: 
      - "../variables/ping-values.yaml"
    tasks:
      - name: ping managed hosts
        ping: 