---
  - name: create file managed servers
    hosts: "{{ group }}"
    gather_facts: "{{ gather_facts }}"
    vars_files: 
      - "../variables/testfile-values.yaml"
    tasks:
      - name: create file in managed servers 
        file:
          path: /tmp/{{ file_name }}
          state: "{{ file_state }}"
          mode: "{{ file_mode }}"
      - name: write "Hello world!" inside the file we just created 
        lineinfile: 
          path: /tmp/{{ file_name }}
          line: "{{ line }}"
          create: yes
      - name: 
        blockinfile:  
          path: /tmp/{{ file_name }}
          block: |
            {{ block }}