---
  - name: create file managed servers
    hosts: "{{ group }}"
    gather_facts: "{{ gather_facts }}"
    vars_files: 
      - "../variables/testfile-values.yaml"
    tasks:
     # Task to create file- values defined in ../variables/testfile-values.yaml
      - name: create file in managed servers 
        file:
          path: /tmp/{{ file_name }}
          state: "{{ file_state }}"
          mode: "{{ file_mode }}"