---
  - name: copy the file to uremote host
    hosts: development 
    tasks: 
      - name: copy the file
        when: ansible_hostname=="application"  
        copy: 
          src: /tmp/index.html
          dest: /var/www/html/
          owner: apache
          group: apache